# Generated by Django 3.2.12 on 2022-07-12 14:12

import analyser.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('windows_engine', '0004_auto_20220712_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('name', models.CharField(default='Undefined name', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('file', models.FileField(storage=analyser.models.RulesStorage(), upload_to='')),
                ('os', models.CharField(choices=[('Windows', 'Windows')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VirustotalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=True)),
                ('analysisId', models.CharField(max_length=256)),
                ('widgetUrl', models.CharField(default='', max_length=500)),
                ('widgetDate', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.JSONField()),
                ('filescan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.filescan')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('threat', models.CharField(default='', max_length=500)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.dump')),
                ('ps_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.psscan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.filescan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('netscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.netscan')),
                ('process', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analyser.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('cmdline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.cmdline')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
