# Generated by Django 3.2.12 on 2022-06-29 12:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('windows_engine', '0003_pslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('name', models.CharField(default='Undefined name', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.analysis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='')),
                ('os', models.CharField(choices=[('Windows', 'Windows')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('threat', models.CharField(default='', max_length=500)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.dump')),
                ('ps_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.psscan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.filescan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('netscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.netscan')),
                ('process', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analyser.process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investigation_id', models.IntegerField(null=True)),
                ('cmdline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.cmdline')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyser.process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
