# Generated by Django 3.2.12 on 2022-07-06 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_alter_rule_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='virustotalanalysis',
            name='widgetDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='virustotalanalysis',
            name='widgetUrl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
