# Generated by Django 3.2.12 on 2022-08-03 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0005_auto_20220803_1323'),
        ('analyser', '0003_alter_rule_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirustotalAnalysisDll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=True)),
                ('analysisId', models.CharField(max_length=256)),
                ('widgetUrl', models.CharField(default='', max_length=500)),
                ('widgetDate', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.JSONField()),
                ('dllList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.dlllist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirustotalAnalysisFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=True)),
                ('analysisId', models.CharField(max_length=256)),
                ('widgetUrl', models.CharField(default='', max_length=500)),
                ('widgetDate', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.JSONField()),
                ('filescan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.filescan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirustotalAnalysisProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ongoing', models.BooleanField(default=True)),
                ('analysisId', models.CharField(max_length=256)),
                ('widgetUrl', models.CharField(default='', max_length=500)),
                ('widgetDate', models.DateTimeField(default=datetime.datetime.now)),
                ('result', models.JSONField()),
                ('processScan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.psscan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='children',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VirustotalAnalysis',
        ),
    ]
