# Generated by Django 3.2.12 on 2022-08-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0005_auto_20220803_1323'),
        ('analyser', '0004_auto_20220803_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_malicious',
        ),
        migrations.RemoveField(
            model_name='process',
            name='ps_scan',
        ),
        migrations.RemoveField(
            model_name='process',
            name='threat',
        ),
        migrations.AddField(
            model_name='process',
            name='ps_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='windows_engine.pslist'),
        ),
    ]
