# Generated by Django 3.2.12 on 2022-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvestigation',
            name='do_clamav',
            field=models.BooleanField(default=False),
        ),
    ]
