version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres:14.1
    restart: always
    env_file:
      - ./secret/volweb.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq3:
    container_name: "rabbitmq3"
    image: rabbitmq:3.9.13
    ports:
      - "5672:5672"
    env_file:
      - ./secret/volweb.env
volumes:
  postgres-data:
