# Generated by Django 3.2.12 on 2022-07-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        ('windows_engine', '0003_pslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cachedump',
            old_name='domain',
            new_name='Domain',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='domain_name',
            new_name='Domainname',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='hash',
            new_name='Hash',
        ),
        migrations.RenameField(
            model_name='cachedump',
            old_name='username',
            new_name='Username',
        ),
        migrations.CreateModel(
            name='RulesResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows_rules_investigation', to='investigations.uploadinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='Handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Offset', models.BigIntegerField()),
                ('Name', models.TextField(null=True)),
                ('HandleValue', models.IntegerField()),
                ('GrantedAccess', models.BigIntegerField()),
                ('Type', models.CharField(max_length=255)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.psscan')),
            ],
        ),
        migrations.CreateModel(
            name='DllList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Base', models.BigIntegerField()),
                ('Name', models.TextField()),
                ('Path', models.TextField()),
                ('Size', models.BigIntegerField()),
                ('LoadTime', models.CharField(max_length=255, null=True)),
                ('File_output', models.CharField(max_length=500)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windows_engine.psscan')),
            ],
        ),
    ]
