# Generated by Django 3.2.12 on 2022-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windows_engine', '0004_auto_20220712_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlllist',
            name='clamav_details',
            field=models.CharField(default='Never analysed', max_length=1024),
        ),
        migrations.AddField(
            model_name='dlllist',
            name='is_clamav_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pslist',
            name='clamav_details',
            field=models.CharField(default='Never analysed', max_length=1024),
        ),
        migrations.AddField(
            model_name='pslist',
            name='is_clamav_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
